from __future__ import annotations

import base64
from datetime import datetime, timezone
from io import BytesIO
from typing import Any

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image, ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _ensure_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _safe_text(value: Any) -> str:
    return str(value or '').strip()


def _build_metric_chart(metrics: list[dict[str, Any]]) -> BytesIO | None:
    metric_items = [metric for metric in metrics if isinstance(metric, dict) and metric.get('values')]
    if not metric_items:
        return None

    chart_count = min(len(metric_items), 4)
    figure, axes = plt.subplots(chart_count, 1, figsize=(8, max(2.8 * chart_count, 3.0)))
    if chart_count == 1:
        axes = [axes]

    for axis, metric in zip(axes, metric_items[:chart_count]):
        values = metric.get('values', [])
        timestamps = metric.get('timestamps', [])
        labels = [str(item)[:19] for item in timestamps] if timestamps else [str(index + 1) for index in range(len(values))]
        axis.plot(range(len(values)), values, marker='o', linewidth=2, color='#2563eb')
        axis.set_title(_safe_text(metric.get('name', 'Metric trend')))
        axis.set_ylabel('Value')
        axis.set_xticks(range(len(labels)))
        axis.set_xticklabels(labels, rotation=35, ha='right', fontsize=8)
        axis.grid(alpha=0.25)

    figure.tight_layout()
    buffer = BytesIO()
    figure.savefig(buffer, format='png', dpi=160, bbox_inches='tight')
    plt.close(figure)
    buffer.seek(0)
    return buffer


def _build_metric_summary(metrics: list[dict[str, Any]]) -> Table | None:
    rows = [['Metric', 'Samples', 'Latest', 'Peak']]
    for metric in metrics:
        if not isinstance(metric, dict):
            continue
        values = metric.get('values', [])
        if not values:
            continue
        rows.append([
            _safe_text(metric.get('name', 'Metric')),
            str(len(values)),
            str(values[-1]),
            str(max(values)),
        ])

    if len(rows) == 1:
        return None

    table = Table(rows, colWidths=[2.2 * inch, 1.0 * inch, 1.2 * inch, 1.2 * inch])
    table.setStyle(
        TableStyle(
            [
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1d4ed8')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#eff6ff')]),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('PADDING', (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def main(args: dict[str, Any]) -> dict[str, Any]:
    title = _safe_text(args.get('title', 'Incident Report'))
    summary = _safe_text(args.get('summary', ''))
    evidence = [_safe_text(item) for item in _ensure_list(args.get('evidence')) if _safe_text(item)]
    metrics = [item for item in _ensure_list(args.get('metrics')) if isinstance(item, dict)]
    recommendations = [_safe_text(item) for item in _ensure_list(args.get('recommendations')) if _safe_text(item)]

    styles = getSampleStyleSheet()
    story = []
    generated_at = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

    story.append(Paragraph(title, styles['Title']))
    story.append(Paragraph(f'Generated by generate-incident-pdf on {generated_at}.', styles['Italic']))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph('Executive Summary', styles['Heading2']))
    story.append(Paragraph(summary or 'No summary was provided.', styles['BodyText']))
    story.append(Spacer(1, 0.18 * inch))

    story.append(Paragraph('Evidence', styles['Heading2']))
    if evidence:
        bullet_items = [ListItem(Paragraph(item, styles['BodyText'])) for item in evidence]
        story.append(ListFlowable(bullet_items, bulletType='bullet'))
    else:
        story.append(Paragraph('No evidence items were provided.', styles['BodyText']))
    story.append(Spacer(1, 0.18 * inch))

    metric_summary = _build_metric_summary(metrics)
    if metric_summary is not None:
        story.append(Paragraph('Metric Summary', styles['Heading2']))
        story.append(metric_summary)
        story.append(Spacer(1, 0.18 * inch))

    chart_buffer = _build_metric_chart(metrics)
    if chart_buffer is not None:
        story.append(Paragraph('Metric Trends', styles['Heading2']))
        story.append(Image(chart_buffer, width=6.8 * inch, height=3.6 * inch))
        story.append(Spacer(1, 0.18 * inch))

    story.append(Paragraph('Recommendations', styles['Heading2']))
    if recommendations:
        recommendation_items = [ListItem(Paragraph(item, styles['BodyText'])) for item in recommendations]
        story.append(ListFlowable(recommendation_items, bulletType='bullet'))
    else:
        story.append(Paragraph('No recommendations were supplied.', styles['BodyText']))

    pdf_buffer = BytesIO()
    document = SimpleDocTemplate(pdf_buffer, pagesize=letter, title=title)
    document.build(story)

    return {
        'pdf_base64': base64.b64encode(pdf_buffer.getvalue()).decode('ascii')
    }